name: bienestar_accion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.10.0
  model_viewer_plus: ^1.10.0
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # 👈 aquí sí va la dependencia

# 👇 este bloque va FUERA de dependencies/dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg.jpeg"

flutter:
  uses-material-design: true

  fonts:
    - family: Forma DJR Deck
      fonts:
        - asset: assets/fonts/FormaDJRDeck-Black-Testing.otf
          weight: 500
        - asset: assets/fonts/FormaDJRDeck-Medium-Testing.otf
          weight: 900

  assets:
    - assets/images/gym.jpg
    - assets/images/side_by_side_logo.png
    # o si quieres toda la carpeta:
    # - assets/images/