// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALH8-GC4fXjxVQdINAs1rseEx-N6x-Q-w',
    appId: '1:428820541328:web:96927eda6e126dd1b54d15',
    messagingSenderId: '428820541328',
    projectId: 'proyecto-76275',
    authDomain: 'proyecto-76275.firebaseapp.com',
    storageBucket: 'proyecto-76275.firebasestorage.app',
    measurementId: 'G-MWWN1Z7DST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZ1uU-yjskeCqOQSDinjCu88aKxDfOws',
    appId: '1:428820541328:android:4bbd07d5a8aa5e6eb54d15',
    messagingSenderId: '428820541328',
    projectId: 'proyecto-76275',
    storageBucket: 'proyecto-76275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWD4mIB7TIyGg8bc1qqPjMaxXDbC_YhoQ',
    appId: '1:428820541328:ios:0778a3292e841f0eb54d15',
    messagingSenderId: '428820541328',
    projectId: 'proyecto-76275',
    storageBucket: 'proyecto-76275.firebasestorage.app',
    iosBundleId: 'com.example.daniboi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWD4mIB7TIyGg8bc1qqPjMaxXDbC_YhoQ',
    appId: '1:428820541328:ios:0778a3292e841f0eb54d15',
    messagingSenderId: '428820541328',
    projectId: 'proyecto-76275',
    storageBucket: 'proyecto-76275.firebasestorage.app',
    iosBundleId: 'com.example.daniboi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALH8-GC4fXjxVQdINAs1rseEx-N6x-Q-w',
    appId: '1:428820541328:web:b123939503162b17b54d15',
    messagingSenderId: '428820541328',
    projectId: 'proyecto-76275',
    authDomain: 'proyecto-76275.firebaseapp.com',
    storageBucket: 'proyecto-76275.firebasestorage.app',
    measurementId: 'G-Y0WXJGQSYD',
  );
}
